export { handlersOnMembersInfoChangeLoad, handlersOnMembersInfoChangeChange, handlersOnMembersInfoChangeSave, handlersOnMembersInfoChangeSubmit } from './InboundPage/MembersInfoChangeTabActions.js';
export { handleOnSalesFollowTaskChange, handleOnSalesFollowTaskSave, handleOnSalesFollowTaskCustomerChange, handleOnSalesFollowTaskLoad } from './InboundPage/SalesFollowTaskTabActions.js';
export { handlersOnProblemFeedbackSave, handlersOnProblemFeedbackChange, handlersOnProblemFeedbackLoad } from './InboundPage/InboundProblemFeedbackTabActions.js';
export { handlerOnVisitPlanNew, handlerOnVisitPlanDeleteItem, handlerOnVisitPlanSave, handlerOnVisitPlanEdit, handlerOnVisitPlanChange } from './InboundPage/VisitPlanTabActions.js';
export { handlerOnTabsSelect } from './InboundPage/InboundTabsActions.js';
export { handlerOnCallRecordQuery, handlerOnCallRecordsChange } from './InboundPage/CallRecordsActions.js';
export { handlerOnQuestionHistoryQeury, handlerOnQuestionHistoryAdditional, handlerOnQuestionHistoryOpen, handlerOnQuestionHistoryQueryChange } from './InboundPage/QuestionHistoryActions.js';
export { handlerOnCustomerVipQuery, handlerOnCustomerVipChange } from './InboundPage/CustomerVipActions.js';
export { handlerOnRecordEditItem, handlerOnRecordDeleteItem, handlerOnRecordSubmit, handlerOnRecordSave, handlerOnRecordChange, handlerOnRecordNew, handlerOnRecordLoad, handleOnRecordOppRefresh } from './InboundPage/ProblemRecordTabActions.js';
export { handlerCustomerSave, handlerCustomerLoad, handleOnCustomerChange } from './InboundPage/CustomerOptActions.js';